name: Generate Snake

on:
  schedule:   # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: sam-lasure2004
          outputs: dist/snake.svg

      - name: Push Snake Animation to Output Branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generated Snake animation"
          add: "dist/snake.svg"
